### ISSUE TITLE
Class Account

### ISSUE THREAD

**Issue by PATCHmiel** [krzesu0/tekstowo#8]
My proposition of Account class

**Fields:**
- name -> str
- first_name -> str
- age -> int
- sex -> Enum[Male, Female]
- gg_id -> int
- registered_date -> datetime
- last_logged_in -> datetime
- town -> str
- region -> str
- about_yourself -> str
- last_content_added -> List[str]
- idols -> List[str]
- invited_users -> List[str]
- Statistics:
     - points -> int
     - rank_place -> int
     - users_invited -> int
     - lyrics_added -> int
     - translations_added -> int
     - videoclips_added -> int
     - soundtracks_added -> int
     - lyrics_edited -> int
     - translations_edited -> int
     - soundtracks_edited -> int

**Methods:**
- getLyricsNames -> List[str]
- getTranslationsNames -> List[str]
- getVideoclipsNames -> List[str]
- getSoundtracksNames -> List[str]

**Comment by mlodybercik** [comment]
Ill start working on it when I have some free time.

**Comment by mlodybercik** [comment]
# Current progress
## Fields:
 - [x] name -> str
 - [x] first_name -> str
 - [x] age -> int
 - [x] sex -> ~~Enum[Male, Female]~~ *bool or int*
`Imo too small to make proper enum, 0 or 1 is sufficient`
 - [x] gg_id -> ~~int~~ ~~*str*~~ **int** 
 - [x] registered_date -> ~~datetime~~ *date*
 - [x] last_logged_in -> ~~datetime~~ *date*
`We dont have any information about time, date is sufficient.`
 - [x] town -> str
 - [x] region -> str
 - [x] about_yourself -> str
 - [x] last_content_added -> List[str or Song]
 - [x] last_idols -> List[artistDraft]
 - [x] last_invited_users -> List[userDraft]
 - [x] last_favourites -> List[Song]
Those `^` four will be implemented *but* will hold only max of `12` most recent items. For each one of them there will be a method to get generator to get whole list.

## Stats:
 - [x] lyrics_added -> int
 - [x] translations_added -> int
 - [x] aideoclips_added -> int
 - [x] soundtracks_added -> int
 - [x] lyrics_edited -> int
 - [x] translations_edited -> int
 - [x] soundtracks_edited -> int
`Easy to implement.` I've placed them in two tuples named added and edited.
 - [x] points -> int
 - [x] rank_place -> int
 - [x] users_invited -> int

## Methods:
 - [x] getLyricsNames -> ~~List[str]~~ *Generator[str or Song]*
 - [x] getTranslationsNames -> ~~List[str]~~ *Generator[str or Song]*
 - [x] getVideoclipsNames -> ~~List[str]~~*Generator[str or Song]*
 - [x] getSoundtracksNames -> ~~List[str]~~ *Generator[str or Song]*
All of these have to return generators. Some guys have **A LOT** of added items, if returning a table it would fetch it for hours. With generators you can take as many as you want. 
 - [x] getInvited -> Generator[str or UserDraft]

**Comment by mlodybercik** [comment]
All of this has been implemented! 🎉🎆
